name: "6.4.3"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Generate Orval 6.4.3
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: 6.4.3/package-lock.json
      - run: npm install
        working-directory: 6.4.3
      - run: npm run generate
        working-directory: 6.4.3
